name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: x64
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.7.19"
        python-version: '3.11'
    - name: Install the project
      run: uv sync --locked --all-extras --dev --group dev
    - name: Publish package
      if: github.event_name == 'release'
      run: |
        uv build
        uv publish --token "${{ secrets.PYPI_API_TOKEN }}"
